"""add process instance and step

Revision ID: 2f3e533f2be4
Revises: d42aa1f3f87c
Create Date: 2025-04-16 20:55:10.237480

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f3e533f2be4'
down_revision = 'd42aa1f3f87c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('process_instances',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('process_id', sa.UUID(), nullable=False),
    sa.Column('current_node_id', sa.UUID(), nullable=True),
    sa.Column('initiator_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('RUNNING', 'COMPLETED', 'TERMINATED', name='processinstancestatus', native_enum=False), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['current_node_id'], ['process_nodes.id'], ),
    sa.ForeignKeyConstraint(['initiator_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['process_id'], ['processes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_process_instances_id'), 'process_instances', ['id'], unique=False)
    op.create_index(op.f('ix_process_instances_process_id'), 'process_instances', ['process_id'], unique=False)
    op.create_table('process_instance_steps',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('instance_id', sa.UUID(), nullable=False),
    sa.Column('node_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('action', sa.String(length=32), nullable=False),
    sa.Column('comment', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['instance_id'], ['process_instances.id'], ),
    sa.ForeignKeyConstraint(['node_id'], ['process_nodes.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_process_instance_steps_id'), 'process_instance_steps', ['id'], unique=False)
    op.create_index(op.f('ix_process_instance_steps_instance_id'), 'process_instance_steps', ['instance_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_process_instance_steps_instance_id'), table_name='process_instance_steps')
    op.drop_index(op.f('ix_process_instance_steps_id'), table_name='process_instance_steps')
    op.drop_table('process_instance_steps')
    op.drop_index(op.f('ix_process_instances_process_id'), table_name='process_instances')
    op.drop_index(op.f('ix_process_instances_id'), table_name='process_instances')
    op.drop_table('process_instances')
    # ### end Alembic commands ### 