"""remove user role add process role

Revision ID: f59c7460dc00
Revises: 49dd5623ead7
Create Date: 2025-04-19 15:53:03.860099

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f59c7460dc00'
down_revision = '49dd5623ead7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('process_roles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('model', sa.String(), nullable=True),
    sa.Column('process_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['process_id'], ['processes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_process_roles_name'), 'process_roles', ['name'], unique=False)
    op.drop_index('ix_user_roles_id', table_name='user_roles')
    op.drop_index('ix_user_roles_name', table_name='user_roles')
    op.drop_constraint('process_nodes_role_id_fkey', 'process_nodes', type_='foreignkey')
    op.drop_table('user_roles')
    op.create_foreign_key(None, 'process_nodes', 'process_roles', ['role_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'process_nodes', type_='foreignkey')
    op.create_foreign_key('process_nodes_role_id_fkey', 'process_nodes', 'user_roles', ['role_id'], ['id'])
    op.create_table('user_roles',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('model', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='user_roles_pkey')
    )
    op.create_index('ix_user_roles_name', 'user_roles', ['name'], unique=False)
    op.create_index('ix_user_roles_id', 'user_roles', ['id'], unique=False)
    op.drop_index(op.f('ix_process_roles_name'), table_name='process_roles')
    op.drop_table('process_roles')
    # ### end Alembic commands ### 