"""update fiels on instance step

Revision ID: 22600a2c1e3b
Revises: e07dfc16714a
Create Date: 2025-04-30 19:38:07.424205

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22600a2c1e3b'
down_revision = 'e07dfc16714a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('process_instance_steps', sa.Column('generated_text', sa.String(), nullable=True))
    op.drop_column('process_instance_steps', 'comment')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('process_instance_steps', sa.Column('comment', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('process_instance_steps', 'generated_text')
    # ### end Alembic commands ### 