"""update table name

Revision ID: 2713fdc8cc05
Revises: 5ad20f663b51
Create Date: 2025-04-23 20:46:08.321395

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2713fdc8cc05'
down_revision = '5ad20f663b51'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('process_role_users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['process_roles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_process_role_users_id'), 'process_role_users', ['id'], unique=False)
    op.create_index(op.f('ix_process_role_users_user_id'), 'process_role_users', ['user_id'], unique=False)
    op.drop_index('ix_process_user_roles_id', table_name='process_user_roles')
    op.drop_index('ix_process_user_roles_user_id', table_name='process_user_roles')
    op.drop_table('process_user_roles')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('process_user_roles',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('role_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['process_roles.id'], name='process_user_roles_role_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='process_user_roles_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='process_user_roles_pkey')
    )
    op.create_index('ix_process_user_roles_user_id', 'process_user_roles', ['user_id'], unique=False)
    op.create_index('ix_process_user_roles_id', 'process_user_roles', ['id'], unique=False)
    op.drop_index(op.f('ix_process_role_users_user_id'), table_name='process_role_users')
    op.drop_index(op.f('ix_process_role_users_id'), table_name='process_role_users')
    op.drop_table('process_role_users')
    # ### end Alembic commands ### 