"""add user profile fields

Revision ID: 2798ef6e8f5b
Revises: 81f51bc631ac
Create Date: 2025-05-18 14:12:15.440908

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2798ef6e8f5b'
down_revision = '81f51bc631ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('personality_traits', sa.ARRAY(sa.String()), nullable=True))
    op.add_column('users', sa.Column('background', sa.TEXT(), nullable=True))
    op.add_column('users', sa.Column('interests', sa.ARRAY(sa.String()), nullable=True))
    op.add_column('users', sa.Column('skills', sa.ARRAY(sa.String()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'skills')
    op.drop_column('users', 'interests')
    op.drop_column('users', 'background')
    op.drop_column('users', 'personality_traits')
    # ### end Alembic commands ### 