"""add birth_date gender profession to user model

Revision ID: 39614c96311a
Revises: 06b1f23fbfb6
Create Date: 2025-04-22 07:44:19.069167

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39614c96311a'
down_revision = '06b1f23fbfb6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('birth_date', sa.Date(), nullable=True))
    op.add_column('users', sa.Column('gender', sa.Enum('MALE', 'FEMALE', 'OTHER', 'PREFER_NOT_TO_SAY', name='gender', native_enum=False), nullable=True))
    op.add_column('users', sa.Column('profession', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'profession')
    op.drop_column('users', 'gender')
    op.drop_column('users', 'birth_date')
    # ### end Alembic commands ### 