"""support multiple roles on one node

Revision ID: 4326a345e1a1
Revises: 38289b0f5bba
Create Date: 2025-05-01 16:59:25.207642

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4326a345e1a1'
down_revision = '38289b0f5bba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('process_node_roles',
    sa.Column('process_node_id', sa.UUID(), nullable=False),
    sa.Column('process_role_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['process_node_id'], ['process_nodes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['process_role_id'], ['process_roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('process_node_id', 'process_role_id')
    )
    op.drop_constraint('process_nodes_role_id_fkey', 'process_nodes', type_='foreignkey')
    op.drop_column('process_nodes', 'role_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('process_nodes', sa.Column('role_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key('process_nodes_role_id_fkey', 'process_nodes', 'process_roles', ['role_id'], ['id'])
    op.drop_table('process_node_roles')
    # ### end Alembic commands ### 