"""add process instance id to process role user

Revision ID: 46fb02f75e46
Revises: bf766a835643
Create Date: 2025-04-24 20:56:56.071112

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46fb02f75e46'
down_revision = 'bf766a835643'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('process_role_users', sa.Column('process_instance_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_process_role_users_process_instance_id'), 'process_role_users', ['process_instance_id'], unique=False)
    op.create_foreign_key(None, 'process_role_users', 'process_instances', ['process_instance_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'process_role_users', type_='foreignkey')
    op.drop_index(op.f('ix_process_role_users_process_instance_id'), table_name='process_role_users')
    op.drop_column('process_role_users', 'process_instance_id')
    # ### end Alembic commands ### 