"""add model field to user role

Revision ID: 49dd5623ead7
Revises: 2f3e533f2be4
Create Date: 2025-04-19 12:51:30.688232

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49dd5623ead7'
down_revision = '2f3e533f2be4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_roles', sa.Column('model', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_roles', 'model')
    # ### end Alembic commands ### 