"""add users table and remove user fields from assistants

Revision ID: 4ab19cbf94c6
Revises: 65dc01ffca4c
Create Date: 2025-07-05 11:09:05.047536

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4ab19cbf94c6'
down_revision: Union[str, None] = '65dc01ffca4c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_first_name'), 'users', ['first_name'], unique=False)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_last_name'), 'users', ['last_name'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.drop_index(op.f('ix_assistants_email'), table_name='assistants')
    op.drop_index(op.f('ix_assistants_first_name'), table_name='assistants')
    op.drop_index(op.f('ix_assistants_last_name'), table_name='assistants')
    op.drop_index(op.f('ix_assistants_username'), table_name='assistants')
    op.drop_column('assistants', 'first_name')
    op.drop_column('assistants', 'email')
    op.drop_column('assistants', 'last_name')
    op.drop_column('assistants', 'username')
    op.drop_column('assistants', 'last_login_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assistants', sa.Column('last_login_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('assistants', sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('assistants', sa.Column('last_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('assistants', sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('assistants', sa.Column('first_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_assistants_username'), 'assistants', ['username'], unique=True)
    op.create_index(op.f('ix_assistants_last_name'), 'assistants', ['last_name'], unique=False)
    op.create_index(op.f('ix_assistants_first_name'), 'assistants', ['first_name'], unique=False)
    op.create_index(op.f('ix_assistants_email'), 'assistants', ['email'], unique=True)
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_last_name'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_first_name'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
