"""fix: revert task assignment and episode initiator to reference assistants

Revision ID: 4b9892dd95bd
Revises: ebf18c4599de
Create Date: 2025-07-05 15:38:14.846519

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b9892dd95bd'
down_revision: Union[str, None] = 'ebf18c4599de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('episodes_initiator_id_fkey'), 'episodes', type_='foreignkey')
    op.create_foreign_key(None, 'episodes', 'assistants', ['initiator_id'], ['id'])
    op.drop_constraint(op.f('tasks_assigned_by_fkey'), 'tasks', type_='foreignkey')
    op.drop_constraint(op.f('tasks_assigned_to_fkey'), 'tasks', type_='foreignkey')
    op.create_foreign_key(None, 'tasks', 'assistants', ['assigned_by'], ['id'])
    op.create_foreign_key(None, 'tasks', 'assistants', ['assigned_to'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.create_foreign_key(op.f('tasks_assigned_to_fkey'), 'tasks', 'users', ['assigned_to'], ['id'])
    op.create_foreign_key(op.f('tasks_assigned_by_fkey'), 'tasks', 'users', ['assigned_by'], ['id'])
    op.drop_constraint(None, 'episodes', type_='foreignkey')
    op.create_foreign_key(op.f('episodes_initiator_id_fkey'), 'episodes', 'users', ['initiator_id'], ['id'])
    # ### end Alembic commands ###
