"""add process role users

Revision ID: 5ad20f663b51
Revises: 9a7491a8522b
Create Date: 2025-04-23 19:46:20.632871

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ad20f663b51'
down_revision = '9a7491a8522b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('process_user_roles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['process_roles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_process_user_roles_id'), 'process_user_roles', ['id'], unique=False)
    op.create_index(op.f('ix_process_user_roles_user_id'), 'process_user_roles', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_process_user_roles_user_id'), table_name='process_user_roles')
    op.drop_index(op.f('ix_process_user_roles_id'), table_name='process_user_roles')
    op.drop_table('process_user_roles')
    # ### end Alembic commands ### 