"""add fields to process instance

Revision ID: 8d2c51de0cc4
Revises: bc9789be50d3
Create Date: 2025-04-22 16:49:11.937003

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d2c51de0cc4'
down_revision = 'bc9789be50d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('process_instances', sa.Column('config', sa.JSON(), nullable=True))
    op.add_column('process_instances', sa.Column('evolution', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('process_instances', 'evolution')
    op.drop_column('process_instances', 'config')
    # ### end Alembic commands ### 