"""add first_name, last_name to assistants and avatar to users

Revision ID: 959e6f88eb7f
Revises: 4ab19cbf94c6
Create Date: 2025-07-05 11:13:56.265425

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '959e6f88eb7f'
down_revision: Union[str, None] = '4ab19cbf94c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assistants', sa.Column('first_name', sa.String(), nullable=True))
    op.add_column('assistants', sa.Column('last_name', sa.String(), nullable=True))
    op.create_index(op.f('ix_assistants_first_name'), 'assistants', ['first_name'], unique=False)
    op.create_index(op.f('ix_assistants_last_name'), 'assistants', ['last_name'], unique=False)
    op.add_column('users', sa.Column('avatar', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'avatar')
    op.drop_index(op.f('ix_assistants_last_name'), table_name='assistants')
    op.drop_index(op.f('ix_assistants_first_name'), table_name='assistants')
    op.drop_column('assistants', 'last_name')
    op.drop_column('assistants', 'first_name')
    # ### end Alembic commands ###
