"""update model fiels

Revision ID: 9a7491a8522b
Revises: 2e44033a7751
Create Date: 2025-04-23 14:54:37.912258

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a7491a8522b'
down_revision = '2e44033a7751'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ### 