"""update relationship

Revision ID: bf766a835643
Revises: 2713fdc8cc05
Create Date: 2025-04-23 21:02:04.924308

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf766a835643'
down_revision = '2713fdc8cc05'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ### 