"""add related type and id to conversation

Revision ID: ce7bfe83560e
Revises: 4326a345e1a1
Create Date: 2025-05-13 16:37:55.838311

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce7bfe83560e'
down_revision = '4326a345e1a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_conversations', sa.Column('related_id', sa.UUID(), nullable=True))
    op.add_column('chat_conversations', sa.Column('related_type', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_conversations', 'related_type')
    op.drop_column('chat_conversations', 'related_id')
    # ### end Alembic commands ### 