"""add learner role to process

Revision ID: e07dfc16714a
Revises: 46fb02f75e46
Create Date: 2025-04-25 09:08:35.393763

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e07dfc16714a'
down_revision = '46fb02f75e46'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('processes', sa.Column('learner_role', sa.String(length=100), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('processes', 'learner_role')
    # ### end Alembic commands ### 