"""update all created_by and user references to point to users table

Revision ID: ebf18c4599de
Revises: 959e6f88eb7f
Create Date: 2025-07-05 15:27:04.059825

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ebf18c4599de'
down_revision: Union[str, None] = '959e6f88eb7f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('assistant_organizations_added_by_fkey'), 'assistant_organizations', type_='foreignkey')
    op.create_foreign_key(None, 'assistant_organizations', 'users', ['added_by'], ['id'])
    op.drop_constraint(op.f('assistants_created_by_fkey'), 'assistants', type_='foreignkey')
    op.create_foreign_key(None, 'assistants', 'users', ['created_by'], ['id'])
    op.drop_constraint(op.f('chat_conversations_created_by_fkey'), 'chat_conversations', type_='foreignkey')
    op.create_foreign_key(None, 'chat_conversations', 'users', ['created_by'], ['id'])
    op.drop_constraint(op.f('episodes_initiator_id_fkey'), 'episodes', type_='foreignkey')
    op.create_foreign_key(None, 'episodes', 'users', ['initiator_id'], ['id'])
    op.drop_constraint(op.f('organizations_created_by_fkey'), 'organizations', type_='foreignkey')
    op.create_foreign_key(None, 'organizations', 'users', ['created_by'], ['id'])
    op.drop_constraint(op.f('scenarios_created_by_fkey'), 'scenarios', type_='foreignkey')
    op.create_foreign_key(None, 'scenarios', 'users', ['created_by'], ['id'])
    op.drop_constraint(op.f('tasks_created_by_fkey'), 'tasks', type_='foreignkey')
    op.drop_constraint(op.f('tasks_assigned_to_fkey'), 'tasks', type_='foreignkey')
    op.drop_constraint(op.f('tasks_assigned_by_fkey'), 'tasks', type_='foreignkey')
    op.create_foreign_key(None, 'tasks', 'users', ['assigned_to'], ['id'])
    op.create_foreign_key(None, 'tasks', 'users', ['assigned_by'], ['id'])
    op.create_foreign_key(None, 'tasks', 'users', ['created_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.create_foreign_key(op.f('tasks_assigned_by_fkey'), 'tasks', 'assistants', ['assigned_by'], ['id'])
    op.create_foreign_key(op.f('tasks_assigned_to_fkey'), 'tasks', 'assistants', ['assigned_to'], ['id'])
    op.create_foreign_key(op.f('tasks_created_by_fkey'), 'tasks', 'assistants', ['created_by'], ['id'])
    op.drop_constraint(None, 'scenarios', type_='foreignkey')
    op.create_foreign_key(op.f('scenarios_created_by_fkey'), 'scenarios', 'assistants', ['created_by'], ['id'])
    op.drop_constraint(None, 'organizations', type_='foreignkey')
    op.create_foreign_key(op.f('organizations_created_by_fkey'), 'organizations', 'assistants', ['created_by'], ['id'])
    op.drop_constraint(None, 'episodes', type_='foreignkey')
    op.create_foreign_key(op.f('episodes_initiator_id_fkey'), 'episodes', 'assistants', ['initiator_id'], ['id'])
    op.drop_constraint(None, 'chat_conversations', type_='foreignkey')
    op.create_foreign_key(op.f('chat_conversations_created_by_fkey'), 'chat_conversations', 'assistants', ['created_by'], ['id'])
    op.drop_constraint(None, 'assistants', type_='foreignkey')
    op.create_foreign_key(op.f('assistants_created_by_fkey'), 'assistants', 'assistants', ['created_by'], ['id'])
    op.drop_constraint(None, 'assistant_organizations', type_='foreignkey')
    op.create_foreign_key(op.f('assistant_organizations_added_by_fkey'), 'assistant_organizations', 'assistants', ['added_by'], ['id'])
    # ### end Alembic commands ###
